### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by volbap** [inaka/PictureViewMaster-iOS#12]
I suggest to remove the unnecessary `-iOS` suffix, so that it looks like:

https://github.com/inaka/PictureViewMaster

**Comment by agerace** [comment]
@ignaciom  ^ , can we do that?

**Comment by elbrujohalcon** [comment]
@agerace @pablolvillar I can

**Comment by elbrujohalcon** [comment]
done

**Comment by agerace** [comment]
jajaja the almighty @elbrujohalcon  strikes again! thanks !
